### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by baldurmen** [im-tomu/im-tomu.github.io#14]
Hi!

Is there a reason http://tomu.im doesn't automatically redirect to the HTTPS version of the website?

**Comment by mithro** [comment]
Does for me?

**Comment by mithro** [comment]
![image](https://user-images.githubusercontent.com/21212/43862919-f135158e-9b0f-11e8-8e50-dcd89990aa20.png)

**Comment by mithro** [comment]
So it appears I had HSTS enabled but not auto-redirect.

I've turned on the auto-redirection option;
```
$ curl -I tomu.im
HTTP/1.1 301 Moved Permanently
Date: Wed, 08 Aug 2018 20:37:40 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Wed, 08 Aug 2018 21:37:40 GMT
Location: https://tomu.im/
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 4474c840042698ad-LAX
```
