### ISSUE TITLE
Outdated u2f link?

### ISSUE THREAD

**Issue by ringerc** [im-tomu/im-tomu.github.io#22]
Per my groups post https://groups.google.com/d/msg/tomu-discuss/qk6oRofL8B0/ae0kj7mXEQAJ  it looks like the link to U2F at https://github.com/im-tomu/chopstx/tree/efm32/u2f may be outdated, with the firmware now hosted at https://github.com/gl-sergei/u2f-token .

@gl-sergei  ?

**Comment by xobs** [comment]
As per your recommendation, I've pointed the link at `gl-sergei/u2f-token`
